# A-Z Movie Dataset (Bollywood + Hollywood)

MOVIES = [
    "Avatar",
    "Avengers Endgame",
    "Avengers Infinity War",
    "Alien",
    "Annabelle",
    "Airlift",
    "Article 15",
    "Batman Begins",
    "Black Panther",
    "Bajrangi Bhaijaan",
    "Bajirao Mastani",
    "Barfi",
    "Bahubali The Beginning",
    "Bahubali 2",
    "Brahmastra",
    "Baby",
    "Baaghi",
    "Baaghi 2",
    "Baaghi 3",
    "Blade Runner",
    "Captain America Civil War",
    "Captain America Winter Soldier",
    "Coco",
    "Conjuring",
    "Chennai Express",
    "Chak De India",
    "Cinderella",
    "Catch Me If You Can",
    "Casino",
    "Cast Away",
    "Dark Knight",
    "Dark Knight Rises",
    "Drishyam",
    "Drishyam 2",
    "Dangal",
    "Dilwale Dulhania Le Jayenge",
    "Dil Chahta Hai",
    "Don",
    "Don 2",
    "Dhoom",
    "Dhoom 2",
    "Dhoom 3",
    "Devdas",
    "Doctor Strange",
    "Deadpool",
    "Django Unchained",
    "Eega",
    "E T",
    "Exorcist",
    "Enthiran",
    "Edge of Tomorrow",
    "English Vinglish",
    "Ek Tha Tiger",
    "Forrest Gump",
    "Fast and Furious",
    "Furious 7",
    "Fast Five",
    "Finding Nemo",
    "Frozen",
    "Frozen 2",
    "Fan",
    "Fifty Shades of Grey",
    "Gladiator",
    "Gangs of Wasseypur",
    "Gully Boy",
    "Guardians of the Galaxy",
    "Gravity",
    "Green Mile",
    "Golmaal",
    "Golmaal Again",
    "Gangubai Kathiawadi",
    "Harry Potter Sorcerers Stone",
    "Harry Potter Chamber Secrets",
    "Harry Potter Prisoner Azkaban",
    "Harry Potter Goblet Fire",
    "Harry Potter Order Phoenix",
    "Harry Potter Half Blood Prince",
    "Harry Potter Deathly Hallows",
    "Home Alone",
    "Hunger Games",
    "Housefull",
    "Housefull 2",
    "Housefull 3",
    "Housefull 4",
    "Happy New Year",
    "Heropanti",
    "Inception",
    "Interstellar",
    "Iron Man",
    "Iron Man 2",
    "Iron Man 3",
    "Independence Day",
    "Insidious",
    "Inside Out",
    "Infinity War",
    "Joker",
    "Jumanji",
    "Jaws",
    "Jab We Met",
    "Jawan",
    "Jodha Akbar",
    "Jurassic Park",
    "Jab Harry Met Sejal",
    "Kabhi Khushi Kabhie Gham",
    "Kuch Kuch Hota Hai",
    "Kal Ho Na Ho",
    "Kabir Singh",
    "Kantara",
    "KGF Chapter 1",
    "KGF Chapter 2",
    "Kill Bill",
    "Kingsman",
    "Kick",
    "Krish",
    "Krrish 3",
    "Lagaan",
    "Life of Pi",
    "La La Land",
    "Lion King",
    "Love Aaj Kal",
    "Lootera",
    "Lage Raho Munna Bhai",
    "Lord of the Rings Fellowship",
    "Mission Impossible",
    "Mission Impossible Fallout",
    "Matrix",
    "Matrix Reloaded",
    "Matrix Revolutions",
    "Mardaani",
    "Munna Bhai MBBS",
    "Moana",
    "My Name is Khan",
    "Mughal E Azam",
    "Night at the Museum",
    "Neerja",
    "Notting Hill",
    "No Time To Die",
    "Nayak",
    "Om Shanti Om",
    "Oppenheimer",
    "Oldboy",
    "October",
    "Ok Jaanu",
    "Pathaan",
    "PK",
    "Padmaavat",
    "Pirates of the Caribbean",
    "Pulp Fiction",
    "Pushpa The Rise",
    "Pushpa 2",
    "Pink",
    "PK Movie",
    "Queen",
    "Quantum of Solace",
    "Rockstar",
    "Rang De Basanti",
    "Raazi",
    "Raees",
    "Rambo",
    "Rocky",
    "RRR",
    "Robot",
    "Ready",
    "Race",
    "Sholay",
    "Singham",
    "Singham Returns",
    "Simmba",
    "Sooryavanshi",
    "Sultan",
    "Stree",
    "Sanju",
    "Swades",
    "Shutter Island",
    "Skyfall",
    "Spider Man Homecoming",
    "Spider Man No Way Home",
    "Spider Man Far From Home",
    "Saving Private Ryan",
    "Scream",
    "Titanic",
    "Terminator",
    "Terminator 2",
    "The Dark Knight",
    "The Avengers",
    "Thor",
    "Thor Ragnarok",
    "Taare Zameen Par",
    "Tamasha",
    "Top Gun Maverick",
    "Twilight",
    "Toy Story",
    "The Conjuring",
    "Uri The Surgical Strike",
    "Up",
    "Us",
    "Vikram",
    "Vikram Vedha",
    "Veer Zara",
    "Vivah",
    "War",
    "Whiplash",
    "Wolf of Wall Street",
    "Wonder Woman",
    "Wake Up Sid",
    "X Men",
    "X Men Days of Future Past",
    "Yeh Jawaani Hai Deewani",
    "Youngistaan",
    "Zindagi Na Milegi Dobara",
    "Zero",
    "Zootopia",
]


def group_by_letter():
    grouped = {}
    for m in MOVIES:
        letter = m.strip()[0].upper()
        grouped.setdefault(letter, []).append(m)
    return grouped


def is_valid_movie(name):
    return name.strip().title() in MOVIES
