# data.py
# A compressed list of common English movies (Capitalized)
MOVIES = [
    "Titanic", "Avatar", "Inception", "Interstellar", "The Dark Knight", "Joker", "Parasite",
    "Avengers", "Iron Man", "Thor", "Captain America", "Black Panther", "Spider-Man",
    "Toy Story", "Finding Nemo", "The Lion King", "Frozen", "Coco", "Moana", "Up",
    "Harry Potter", "Lord of the Rings", "Star Wars", "Jurassic Park", "Matrix",
    "Gladiator", "Rocky", "Rambo", "Terminator", "Alien", "Predator",
    "Pulp Fiction", "Reservoir Dogs", "Kill Bill", "Django Unchained", "The Hateful Eight",
    "Forrest Gump", "Cast Away", "Green Mile", "Catch Me If You Can", "The Departed",
    "Shutter Island", "The Revenant", "Wolf of Wall Street", "Great Gatsby",
    "La La Land", "Whiplash", "Birdman", "The Shape of Water", "Bohemian Rhapsody",
    "Jaws", "E.T.", "Close Encounters", "Schindler List", "Saving Private Ryan",
    "Band of Brothers", "Pacific Rim", "Godzilla", "Kong", "Transformers",
    "Fast and Furious", "Mission Impossible", "James Bond", "Kingsman", "Johnny English",
    "Home Alone", "Mrs. Doubtfire", "Jumanji", "Night at the Museum",
    "Twilight", "Hunger Games", "Divergent", "Maze Runner", "Percy Jackson",
    "Men in Black", "Independence Day", "War of the Worlds", "Edge of Tomorrow",
    "Top Gun", "Days of Thunder", "The Rookie", "Jerry Maguire",
    "Pretty Woman", "Runaway Bride", "Notting Hill", "Eat Pray Love",
    "Bruce Almighty", "Ace Ventura", "The Mask", "Dumb and Dumber", "Liar Liar",
    "Hangover", "Old School", "Wedding Crashers", "Step Brothers", "Anchorman",
    "Scarface", "Goodfellas", "Casino", "Godfather", "Sopranos",
    "Breaking Bad", "Better Call Saul", "Walking Dead", "Game of Thrones",
    "Wonder Woman", "Aquaman", "Flash", "Batman", "Superman", "Suicide Squad",
    "Deadpool", "Wolverine", "X-Men", "Fantastic Four", "Ghost Rider",
    "Blade Runner", "Mad Max", "Road Warrior", "Beyond Thunderdome",
    "Exorcist", "Omen", "Ring", "Grudge", "Conjuring", "Insidious", "Sinister",
    "Saw", "Hostel", "Texas Chainsaw", "Halloween", "Friday the 13th",
    "Nightmare on Elm Street", "Scream", "I Know What You Did Last Summer",
    "Cinderella", "Snow White", "Sleeping Beauty", "Beauty and the Beast",
    "Aladdin", "Mulan", "Hercules", "Tarzan", "Pocahontas", "Lilo and Stitch",
    "Descendants", "High School Musical", "Camp Rock", "Zac Efron", "Vanessa Hudgens",
    "Mamma Mia", "ABBA", "Grease", "Dirty Dancing", "Saturday Night Fever",
    "Chicago", "Cabaret", "West Side Story", "Sound of Music", "Mary Poppins",
    "Ben Hur", "Ten Commandments", "Prince of Egypt", "Noah", "Passion of the Christ",
    "Life of Pi", "Slumdog Millionaire", "Gandhi", "Lagaan", "Dangal",
    "Three Idiots", "PK", "Sanju", "Padmaavat", "Bajirao Mastani",
    "My Name is Khan", "Kabhi Khushi Kabhie Gham", "Kuch Kuch Hota Hai", "Dilwale",
    "Happy New Year", "Chennai Express", "Don", "Raees", "Zero", "Fan",
    "Sultan", "Sultan", "Dangal", "Secret Superstar", "Taare Zameen Par",
    "Rang De Basanti", "Rang De Basanti", "Dil Chahta Hai", "Zindagi Na Milegi Dobara",
    "Yeh Jawaani Hai Deewani", "Wake Up Sid", "Ajab Prem Ki Ghazab Kahani",
    "Barfi", "Jab We Met", "Love Aaj Kal", "Cocktail", "Anjaana Anjaani",
    "Student of the Year", "Humpty Sharma Ki Dulhania", "Badrinath Ki Dulhania",
    "War", "Bang Bang", "Hrithik Roshan", "Tiger", "Pathaan", "Jawan",
    "Robot", "Enthiran", "2.0", "Kabali", "Kaala", "Darbar", "Mersal",
    "Baahubali", "Bahubali", "Magadheera", "Eega", "RRR", "Pushpa",
    "KGF", "Kantara", "Vikram", "Leo", "Ponniyin Selvan", "Mani Ratnam",
    "Dil Se", "Dil Se", "Roja", "Bombay", "Yuva", "Ok Kanmani", "O Kadhal Kanmani",
    "Queen", "Tanu Weds Manu", "English Vinglish", "Neerja", "Mardaani",
    "Baby", "Naam Shabana", "Batla House", "Romeo Akbar Walter", "Bhuj",
    "Bhool Bhulaiyaa", "Stree", "Go Goa Gone", "Mumbai Saga", "Sooryavanshi",
    "Simmba", "Singham", "Raid", "Special 26", "Jolly LLB", "Munnabhai",
    "Lage Raho Munna Bhai", "3 Idiots", "Pk", "Sanju", "Dangal"
]

# Helper function to search (case insensitive)
def is_valid_movie(name):
    return name.strip().title() in MOVIES
