# dialogues.py
# Bollywood Movie Dialogues Data

DIALOGUES = [
    ("Pushpa, I hate tears...", "Pushpa The Rise"),
    ("Rishtey mein toh hum tumhare baap lagte hain...", "Wanted"),
    ("Ek chutki sindoor ki keemat tum kya jaano Ramesh Babu...", "Dilwale Dulhania Le Jayenge"),
    ("Babu Moshai, zindagi badi honi chahiye, lambi nahi...", "Anand"),
    ("Don ko pakadna mushkil hi nahi, namumkin hai...", "Don"),
    ("Mere paas Maa hai...", "Deewaar"),
    ("Jaadu ki jhappi...", "Munna Bhai MBBS"),
    ("All izz well...", "3 Idiots"),
    ("Tareekh pe tareekh, tareekh pe tareekh...", "Damini"),
    ("Aaj khush toh bahut hoge...", "Sholay"),
    ("Kitne aadmi the?", "Sholay"),
    ("Mogambo khush hua...", "Mr India"),
    ("Koi kahe kehta rahe...", "Dil Chahta Hai"),
    ("Hum jahan khade hote hain, line wahi se shuru hoti hai...", "Lage Raho Munna Bhai"),
    ("Palat... Palat...", "DDLJ"),
    ("Kabhi Kabhie Mere Dil Mein Khayal Aata Hai...", "Kabhi Kabhie"),
    (" picture abhi baaki hai mere dost...", "Om Shanti Om"),
    ("Apun ka time aayega...", "Gangs of Wasseypur"),
    ("Zindagi mein safar suhana...", "Jab We Met"),
    ("Tussi jaa rahe ho? Tussi na jao...", "Dilwale Dulhania Le Jayenge"),
    ("Mere Karan Arjun aayenge...", "Karan Arjun"),
    ("Aazadi badi cheez hai...", "Rang De Basanti"),
    ("Insaan ka sirf ek dil hota hai...", "Jaane Tu... Ya Jaane Na"),
    ("Jab tak iske andar jaan hai, tab tak umeed hai...", "Zindagi Na Milegi Dobara"),
    ("Bhai yeh sach hai...", "Shivaay"),
    ("Thappad se darr nahi lagta...", "Dangal"),
    ("Chennai Express going to Chennai...", "Chennai Express"),
    ("Sattu pe bhaari...", "Phir Hera Pheri"),
    ("Ghar ek mandir hai...", "Hum Aapke Hain Koun"),
    ("Mere dost ne mujhe zinda rehne diya...", "Khosla Ka Ghosla"),
    ("Ab main batata hoon ke main kaun hoon...", "Don 2"),
    ("Padosi ek se dabav toh nahi dega...", "Munnabhai MBBS"),
    ("Chamkiladi...", "Andhadhun"),
    ("Main chup rahoongi, main gungunaa rahoongi...", "Raazi"),
    ("Mard Ko Dard Nahi Hota", "Mard Ko Dard Nahi Hota")
]
